/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dash_bls_BlsJni */
#include <iostream>
#include "bls.hpp"

#ifndef _Included_org_dash_bls_BlsJni
#define _Included_org_dash_bls_BlsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dash_bls_BlsJni
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_dash_bls_DashBlsJni_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_dash_bls_BlsJni
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_dash_bls_DashBlsJni_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_dash_bls_BlsJni
 * Method:    callBls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dash_bls_DashBlsJni_callBls
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
