/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dash_bls_DashBlsJni */

#ifndef _Included_org_dash_bls_DashBlsJni
#define _Included_org_dash_bls_DashBlsJni
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     org_dash_bls_DashBlsJni
     * Method:    publicKeyFingerprint
     * Signature: ([I)J
     */
    JNIEXPORT jlong JNICALL Java_org_dash_bls_DashBlsJni_publicKeyFingerprint
    (JNIEnv *, jobject, jintArray);

    /*
     * Class:     org_dash_bls_DashBlsJni
     * Method:    nativePublicKeyFingerprint
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_org_dash_bls_DashBlsJni_nativeSignMessage
    (JNIEnv *, jobject);

    /*
     * Class:     org_dash_bls_DashBlsJni
     * Method:    generatePrivateKey
     * Signature: ([I)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_org_dash_bls_DashBlsJni_generatePrivateKey
    (JNIEnv *, jobject, jintArray);

    /*
     * Class:     org_dash_bls_DashBlsJni
     * Method:    generatePublicKey
     * Signature: ([B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_org_dash_bls_DashBlsJni_generatePublicKey
    (JNIEnv *, jobject, jbyteArray);

    /*
     * Class:     org_dash_bls_DashBlsJni
     * Method:    signMessage
     * Signature: ([B[I)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_org_dash_bls_DashBlsJni_signMessage
    (JNIEnv *, jobject, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
